#!/usr/bin/env python3

import thermalmodel.thermalmodel as tm
import thermalmodel.links as links

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#                                Model description
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

model_description = [

    (  # HSN
        'Antenna-Plate',  # HSN name
        {  # HSN parameters
            'mass': 0.01,
            'heatCapacity': 887,
            'heatGeneration': 0,
            'temperature': 22,
        },
        [  # list of attached IFN
            (
                'Antenna-Plate-bottom',  # IFN name
                {  # IFN parameters
                    'emissivity': 0.045,
                    'absorptivity': 0,
                },
                [ ]
            ),
        ]
    ),

    (
        'SSI',
        {
            'mass': 0.01,
            'heatCapacity': 887,
            'heatGeneration': 0,
            'temperature': 22,
        },
        [
            (
                'SSI-top',
                {
                    'emissivity': 0.045,
                    'absorptivity': 0,
                },
                [
                    (
                        'SSI-Antenna-Plate-bottom', ('Antenna-Plate', 'Antenna-Plate-bottom'),
                        [
                            links.ContactLink,
                        ],
                        {
                            'contactArea': 0.003,       # used by contact calculations
                            'resistance': 0.05,         # used by contact calculations
                        }
                    ),
                ]
            ),
            (
                'SSI-side',  # IFN name
                {  # IFN parameters
                    'emissivity': 0.045,
                    'absorptivity': 0,
                },
                [ ]
            ),
            (
                'SSI-bottom',
                {
                    'emissivity': 0.045,
                    'absorptivity': 0,
                },
                [
                    (
                        'SSI-MAGcoilY-top', ('MAGcoilY', 'MAGcoilY-top'),
                        [
                            links.RadiationLink,
                        ],
                        {
                            'radiationArea1': 0.002,  # used by radiation calculations
                            'radiationArea2': 0.002,  # used by radiation calculations
                            'viewingFactor': 0.8,     # used by radiation calculations
                        }
                    ),
                ]
            ),
        ]
    ),

]

model_description.append(
    (
        'MS-Z+',
        {
            'mass': 0.03,
            'heatCapacity': 887,
            'heatGeneration': 0,
            'temperature': 22,
        },
        [
            (
                'MS-Z+-inner',
                {
                    'emissivity': 0.045,
                    'absorptivity': 0,
                },
                [ ]  # links to other IFN
            ),
            (
                'MS-Z+-outer',
                {
                    'emissivity': 0.045,
                    'absorptivity': 0,
                },
                [
                [
                    (
                        'MS-Z+-SSI-side', ('SSI', 'SSI-side'),
                        [
                            links.ContactLink,
                        ],
                        {
                            'contactArea': 0.000108,       # used by contact calculations
                            'resistance': 0.05,            # used by contact calculations
                        }
                    ),
                ]
            ),
        ]
    )
)

model_description.append(

    (  # HSN
        'MAGcoilY',  # HSN name
        {  # HSN parameters
            'mass': 0.015,
            'heatCapacity': 376,
            'heatCapacity': 887,  # TODO: which heatCapacity to use? Taken from second redefinition
            'heatGeneration': 0,
            'temperature': 22,
        },
        [  # list of attached IFN
            (
                'MAGcoilY-top',  # IFN name
                {  # IFN parameters
                    'emissivity': 0.045,
                    'absorptivity': 0,
                },
                [ ]  # links to other IFN
            ),
            (
                'MAGcoilY-outercirc',
                {
                    'emissivity': 0.045,
                    'absorptivity': 0,
                },
                [
                    (
                        'MAGcoilY-MS-Z+-inner', ('MS-Z+', 'MS-Z+-inner'),
                        [
                            links.RadiationLink,
                        ],
                        {
                            'radiationArea1': 0.000892,  # used by radiation calculations
                            'radiationArea2': 2.4,   # used by radiation calculations
                            'viewingFactor': 2.4,    # used by radiation calculations
                        }
                    ),
                ]
            ),
            (
                'MAGcoilY-innercirc',
                {
                    'emissivity': 0.045,
                    'absorptivity': 0,
                },
                [
                    (
                        'MAGcoilY-MS-Z+-inner2', ('MS-Z+', 'MS-Z+-inner'),  # TODO: duplicate IFN key entry leads to error; rename to be unique
                        [
                            links.RadiationLink,
                        ],
                        {
                            'radiationArea1': 0.0042,    # used by radiation calculations
                            'radiationArea2': 0.0035,    # used by radiation calculations
                            'viewingFactor': 0.45,       # used by radiation calculations
                        }
                    ),
                ]
            ),
        ]
    )
)

model_description.append(
    (  # HSN
        'Batteries',  # HSN name
        {  # HSN parameters
            'mass': 0.032,
            'heatCapacity': 887,
            'heatGeneration': 0,
            'temperature': 22,
        },
        [  # list of attached IFN
            (
                'BAT-curved',  # IFN name
                {  # IFN parameters
                    'emissivity': 0.045,
                    'absorptivity': 0,
                },
                [ ]  # links to other IFN
            ),
            (
                'BAT-flat-face',
                {
                    'emissivity': 0.045,
                    'absorptivity': 0,
                },
                [ ]
            ),
        ]
    )
)

model_description.append(
    (
        'EPS',
        {
            'mass': 0.013,
            'heatCapacity': 387,
            'heatGeneration': 0.2,
            'temperature': 22,
        },
        [
            (
                'EPS-top',
                {
                    'emissivity': 0.03,
                    'absorptivity': 0,
                },
                [ ]
            ),
            (
                'EPS-bottom',
                {
                    'emissivity': 0.03,
                    'absorptivity': 0,
                },
                [ ]
            ),
                    (
                        'Batteries-EPS-top', ('Batteries', 'BAT-curved'),
                        [
                            links.RadiationLink,
                        ],
                        {
                            'radiationArea1': 0.008,    # used by radiation calculations
                            'radiationArea2': 0.004,    # used by radiation calculations
                            'viewingFactor': 0.4,       # used by radiation calculation
                        }
                    ),
                    (
                        'EPS-BAT-flat-face', ('Battery', 'BAT-flat-face'),
                        [
                            links.ConductionLink,
                        ],
                        {
                            'conductionArea': 0.012,
                            'conductivity': 385,
                            'length': 0.11,
                        }
                    ),
                ]
            ),
        ]
    )
)

model_description.append(
    (
        '3C2',
        {
            'mass': 0.02,
            'heatCapacity': 387,
            'heatGeneration': 2,
            'temperature': 22,
        },
        [
            (
                '3C2-top',
                {
                    'emissivity': 0.03,
                    'absorptivity': 0,
                },
                [ ]
            ),
            (
                '3C2-bottom',
                {
                    'emissivity': 0.03,
                    'absorptivity': 0,
                },
                [ ]
            ),
                    (
                        '3C2-EPS-bottom', ('EPS', 'EPS-bottom'),
                        [
                            links.RadiationLink,
                        ],
                        {
                            'radiationArea1': 0.008,    # used by radiation calculations
                            'radiationArea2': 0.008,    # used by radiation calculations
                            'viewingFactor': 0.799,     # used by radiation calculation
                        }
                    ),
                    (
                        '3C2-EPS-bottom', ('EPS', 'EPS-bottom'),
                        [
                            links.ConductionLink,
                        ],
                        {
#                             'conductionArea': 0.012,
#                             'conductivity': 385,
#                             'length': 0.11,
                        }
                    ),
                ]
            ),
        ]
    )
)

model_description.append(
    (
        'SSII',
        {
            'mass': 0.01,
            'heatCapacity': 887,
            'heatGeneration': 0,
            'temperature': 22,
        },
        [
            (
                'SSII-top',
                {
                    'emissivity': 0.03,
                    'absorptivity': 0,
                },
                [ ]
            ),
            (
                'SSII-side',
                {
                    'emissivity': 0.03,
                    'absorptivity': 0,
                },
                [ ]
            ),
                    (
                        'SSII-MS-Z+-inner', ('MS-Z+', 'MS-Z+-inner'),
                        [
                            links.ContactLink,
                        ],
                        {
                            'contactArea': 0.00044,    
                            'resistance': 0.05,    
                        }
                    ),
     (
           'MS-Z-',
            {
                'mass': 0.03,
                'heatCapacity': 887,
                'heatGeneration': 0,
                'temperature': 22,
        },
        [
            (
                'MS-Z--inner',
                {
                    'emissivity': 0.045,
                    'absorptivity': 0,
                },
                [ ]
             ),
             (
                'MS-Z--outer',
                {
                    'emissivity': 0.045,
                    'absorptivity': 0,
                },
                [ ]
            ),
                [
                    (
                        'SSII-MS-Z--inner', ('MS-Z-', 'MS-Z--inner'),
                        [
                            links.ContactLink,
                        ],
                        {
                            'contactArea': 0.00044,       # used by contact calculations
                            'resistance': 0.05,           # used by contact calculations
                        }
                    ),
                ]
            ),
        ]
    )
)

model_description.append(
    (
        'SSIII',
        {
            'mass': 0.01,
            'heatCapacity': 887,
            'heatGeneration': 0,
            'temperature': 22,
        },
        [
            (
                'SSIII-side',
                {
                    'emissivity': 0.03,
                    'absorptivity': 0,
                },
                [ ]
            ),
            (
                'SSIII-bottom',
                {
                    'emissivity': 0.03,
                    'absorptivity': 0,
                },
                [ ]
            ),
                    (
                        'SSIII-MS-Z+-inner', ('MS-Z+', 'MS-Z+-inner'),
                        [
                            links.ContactLink,
                        ],
                        {
                            'contactArea': 0.00044,    
                            'resistance': 0.05,    
                        }
                    ),
                [
                    (
                        'SSIII-MS-Z--inner', ('MS-Z-', 'MS-Z--inner'),
                        [
                            links.ContactLink,
                        ],
                        {
                            'contactArea': 0.00044,       # used by contact calculations
                            'resistance': 0.05,           # used by contact calculations
                        }
                    ),
                ]
            ),
        ]
    )
)


model_description.append(
    (
        'Panel-Z-',
        {
            'mass': 0.03,
            'heatCapacity': 887,
            'heatGeneration': 0,
            'temperature': 22,
        },
        [
            (
                'Panel-Z--inner',
                {
                    'emissivity': 0.03,
                    'absorptivity': 0,
                },
                [ ]
            ),
            (
                'Panel-Z--outer',
                {
                    'emissivity': 0.03,
                    'absorptivity': 0,
                },
                [ ]
            ),
                    (
                        'Panel-Z--BAT-curved', ('Batteries', 'BAT-curved'),
                        [
                            links.RadiationLink,
                        ],
                        {
                             'radiationArea1': 0.008,    # used by radiation calculations
                             'radiationArea2': 0.004,    # used by radiation calculations
                             'viewingFactor': 0.15,     
                        }
                    ),
                [
                    (
                        'Panel-Z--EPS-top', ('EPS', 'EPS-top'),
                        [
                            links.RadiationLink,
                        ],
                        {
                            'radiationArea1': 0.008,       # used by contact calculations
                            'radiationArea2': 0.004,          # used by contact calculations
                            'viewingFactor': 0.15,
                        }
                    ),
                ]
            [
                    (
                        'Panel-Z--3C2-top', ('3C2', '3C2-top'),
                        [
                            links.RadiationLink,
                        ],
                        {
                            'radiationArea1': 0.008,      
                            'radiationArea2': 0.004,          
                            'viewingFactor': 0.06,
                        }
                    ),
                ]
            ),
        ]
    )
)
            
model_description.append(
    (
        'Panel-X+',
        {
            'mass': 0.03,
            'heatCapacity': 887,
            'heatGeneration': 0,
            'temperature': 22,
        },
        [
            (
                'Panel-X+-inner',
                {
                    'emissivity': 0.03,
                    'absorptivity': 0,
                },
                [ ]
            ),
            (
                'Panel-X+-outer',
                {
                    'emissivity': 0.03,
                    'absorptivity': 0,
                },
                [ ]
            ),
                    (
                        'Panel-X+-BAT-curved', ('Batteries', 'BAT-curved'),
                        [
                            links.RadiationLink,
                        ],
                        {
                             'radiationArea1': 0.008,    # used by radiation calculations
                             'radiationArea2': 0.004,    # used by radiation calculations
                             'viewingFactor': 0.15,     
                        }
                    ),
                [
                    (
                        'Panel-X+-EPS-top', ('EPS', 'EPS-top'),
                        [
                            links.RadiationLink,
                        ],
                        {
                            'radiationArea1': 0.008,       # used by contact calculations
                            'radiationArea2': 0.004,          # used by contact calculations
                            'viewingFactor': 0.15,
                        }
                    ),
                ]
            [
                    (
                        'Panel-X+-MS-Z--outer', ('MS-Z-', 'MS-Z--outer'),
                        [
                            links.ContactLink,
                        ],
                        {
                            'contactArea': 0.0004,      
                            'resistance': 0.05,          
                        }
                    ),
                ]
            ),
        ]
    )
)

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#                      Create ThermalModel simulation class
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

thermalmodel = tm.ThermalModel(
    simulation_duration=0.1666 * 60,  # seconds
    timestep=1,  # seconds
    model_description=model_description,
)

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#                                 Run Simulation
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

thermalmodel.simulate()
# thermalmodel.save()
