#!/usr/bin/env python3

import thermalmodel.thermalmodel as tm
import thermalmodel.links as links

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#                                Model description
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

model_description = [

    (  # HSN
        'Antenna-Plate',  # HSN name
        {  # HSN parameters
            'mass': 0.01,
            'heatCapacity': 887,
            'heatGeneration': 0,
            'temperature': 22,
        },
        [  # list of attached IFN
            (
                'Antenna-Plate-bottom',  # IFN name
                {  # IFN parameters
                    'emissivity': 0.045,
                    'absorptivity': 0,
                },
                [ ]
            ),
        ]
    ),

    (
        'SSI',
        {
            'mass': 0.01,
            'heatCapacity': 887,
            # heat generation is assumed 0 if not specified
            'temperature': 22,
        },
        [
            (
                'SSI-top',
                {
                    'emissivity': 0.045,
                    'absorptivity': 0,
                },
                [
                    (
                        'SSI-Antenna-Plate-bottom', ('Antenna-Plate', 'Antenna-Plate-bottom'),
                        [
                            links.ContactLink,
                        ],
                        {
                            'contactArea': 0.003,       # used by contact calculations
                            'resistance': 0.05,         # used by contact calculations
                        }
                    ),
                ]
            ),
        ]
    ),

]


model_description = [

    (  # HSN
        'SSI',  # HSN name
        {  # HSN parameters
            'mass': 0.01,
            'heatCapacity': 887,
            'heatGeneration': 0,
            'temperature': 22,
        },
        [  # list of attached IFN
            (
                'SSI-side',  # IFN name
                {  # IFN parameters
                    'emissivity': 0.045,
                    'absorptivity': 0,
                },
                [ ]
            ),
        ]
    ),

    (
        'MS-Z+',
        {
            'mass': 0.03,
            'heatCapacity': 887,
            # heat generation is assumed 0 if not specified
            'temperature': 22,
        },
        [
            (
                'MS-Z+-inner',
                {
                    'emissivity': 0.045,
                    'absorptivity': 0,
                },
                [
                    (
                        'MS-Z+-SSI-side', ('SSI', 'SSI-side'),
                        [
                            links.ContactLink,
                        ],
                        {
                            'contactArea': 0.000108,       # used by contact calculations
                            'resistance': 0.05,            # used by contact calculations
                        }
                    ),
                ]
            ),
        ]
    ),

]



# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#                      Create ThermalModel simulation class
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

thermalmodel = tm.ThermalModel(
    simulation_duration=0.1666 * 60,  # seconds
    timestep=1,  # seconds
    model_description=model_description,
)

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#                                 Run Simulation
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

thermalmodel.simulate()
# thermalmodel.save()
