classDiagram


class Node {
    -Float temperature
    +getTemperature() Float
}

class HeatStorageNode {
    +Float mass
    +Float heatCapacity
    +Dict~String, InterfaceNode~ interfaces
    +computeInterfaceTemperatures()
    +sumInterfaceTemperatures()
    +addInterfaceNode(name, parameters)
    +addInterfaceLink(interfaceName, linkName, node2, parameters)
    +HeatStorageNode(parameters)
}

class InterfaceNode {
    +HeatStorageNode referenceNode
    +Dict~String, Link~ interfaceLinks
    -Float heatExchange
    -Float emissivity
    -Float absorptivity
    -Float interfaceArea
    +computeHeatExchange() Float
    +addLink(name, node2, linkTypes, parameters)
    +InterfaceNode(referenceNode, parameters)
}

class Link {
    +InterfaceNode node1
    +InterfaceNode node2
    +List~LinkType~ linkTypes
    +Dict parameters
    +computeHeatExchange() Float
    +Link(node1, node2, List~Type[LinkType]~ linkTypes, parameters)
}


class LinkType {
    <<Abstract>>
    +Dict options
    +InterfaceNode node1
    +InterfaceNode node2
    -float resistance
    -float length
    -float area
    -float conductivity
    -float viewingFactor
    +computeViewingFactor() Float
    +computeHeatExchange() Float
    +LinkType(options)
}

class RadiationLink {
    -Float radiationArea1
    -Float radiationArea2
}

class ContactLink {
    -Float contactArea
}

class ConductionLink {
    -Float conductionArea
}

HeatStorageNode --|> Node
InterfaceNode --|> Node

Manual --|> LinkType
RadiationLink --|> LinkType
ContactLink --|> LinkType
ConductionLink --|> LinkType
AmbientLink --|> LinkType
VacuumChamberLink --|> LinkType

Link "1..*" -- "2" InterfaceNode

InterfaceNode "1..*" -- "1" HeatStorageNode

LinkType -- Link
LinkType -- InterfaceNode
